# This file contains values from Cookiecutter

default_context:
  project_name: "conftier"
  project_description: "Multi-level configuration framework"
  organization: "conftier"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "Undertone0809"
  email: "zeeland4work@gmail.com"
  version: "0.0.1"
  line_length: "88"
  create_example_template: "cli"
